server:
  port: 9002
spring:
  application:
    name: nacos-provider-server
  cloud:
    nacos:
      server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'