server:
  port: 9527

spring:
  application:
    name: gateway
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        register: true
    gateway:
      discovery:
        locator:
          enabled: true #开启从注册中心动态创建路由功能，利用微服务名称进行路由
      routes:
        - id: mygateway
          uri: lb://consul-openfeign-server  #服务端 service_id
          predicates:
            - Path=/consumer/payment/consul