server:
  port: 8002
spring:
  application:
    name: cloud-provider-service #微服务名称
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root

#eureka客户端（微服务提供者、消费者）
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    #eureka服务地址
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka #集群版
  instance:
    prefer-ip-address: true
    instance-id: payment8002
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.servyou.cloud.pojo
