server:
  port: 3344
spring:
  application:
    name: microservicecloud-config-server
  cloud:
    #注册consul
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
    #配置中心
    config:
      server:
        git:
          uri: https://github.com/13237118211/microservicecloud-config.git
          search-paths:
            - microservicecloud-config
      label: master
  #整合消息总线Bus 刷新服务端发送消息到mq然后客户端再订阅
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
#暴露监控断点 基于actuator
management:
  endpoints:
    web:
      exposure:
        include: 'bus-refresh'