server:
  port: 8801
spring:
  application:
    name: cloud-stream-rabbitmq-provider
  cloud:
    stream:
      bindings:
        output:
          destination: studyExchange #定义要使用的Exchange的名称
          content-type: application/json
          binder: defaultRabbit #指定要使用的binder对象（mq类型及配置）
      binders:
        defaultRabbit:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                port: 5672
                username: guest
                password: guest
    consul:
      host: localhost
      port: 8500
      discovery:
        hostname: 127.0.0.1
        service-name: ${spring.application.name}
